---
# deploy-qbittorrent.yml

- name: Deploy qBittorrent with VPN
  hosts: homelab
  become: true

  vars_files:
    - ../compose-configs/qbittorrent/vars.yml

  roles:
    - role: docker-compose-app
      vars:
        app_name: qbittorrent
        env_template: .env.j2
    - role: qbittorrent_settings
